In [2]:
from json_to_dict import get_data

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = get_data()

In [9]:
list = []
for date in df.keys():
    for ele in df[date]:
        if ele['category'] not in list and ele['category'][0] == "O":
            list.append(ele['category'])
            print(ele['category'])
print(list)

print(len(list))

Open Ended Schemes ( Debt Scheme - Overnight Fund )
Open Ended Schemes ( Debt Scheme - Liquid Fund )
Open Ended Schemes ( Other Scheme - Other  ETFs )
Open Ended Schemes ( Money Market )
Open Ended Schemes ( Equity Scheme - Multi Cap Fund )
Open Ended Schemes ( Equity Scheme - Large Cap Fund )
Open Ended Schemes ( Equity Scheme - Large & Mid Cap Fund )
Open Ended Schemes ( Equity Scheme - Mid Cap Fund )
Open Ended Schemes ( Equity Scheme - Small Cap Fund )
Open Ended Schemes ( Equity Scheme - Dividend Yield Fund )
Open Ended Schemes ( Equity Scheme - Value Fund )
Open Ended Schemes ( Equity Scheme - Contra Fund )
Open Ended Schemes ( Equity Scheme - Focused Fund )
Open Ended Schemes ( Equity Scheme - Sectoral/ Thematic )
Open Ended Schemes ( Equity Scheme - ELSS )
Open Ended Schemes ( Debt Scheme - Ultra Short Duration Fund )
Open Ended Schemes ( Debt Scheme - Low Duration Fund )
Open Ended Schemes ( Debt Scheme - Money Market Fund )
Open Ended Schemes ( Debt Scheme - Short Duration Fund )
Open Ended Schemes ( Debt Scheme - Medium Duration Fund )
Open Ended Schemes ( Debt Scheme - Medium to Long Duration Fund )
Open Ended Schemes ( Debt Scheme - Long Duration Fund )
Open Ended Schemes ( Debt Scheme - Dynamic Bond )
Open Ended Schemes ( Debt Scheme - Corporate Bond Fund )
Open Ended Schemes ( Debt Scheme - Credit Risk Fund )
Open Ended Schemes ( Debt Scheme - Banking and PSU Fund )
Open Ended Schemes ( Debt Scheme - Gilt Fund )
Open Ended Schemes ( Debt Scheme - Gilt Fund with 10 year constant duration )
Open Ended Schemes ( Debt Scheme - Floater Fund )
Open Ended Schemes ( Hybrid Scheme - Conservative Hybrid Fund )
Open Ended Schemes ( Hybrid Scheme - Balanced Hybrid Fund )
Open Ended Schemes ( Hybrid Scheme - Aggressive Hybrid Fund )
Open Ended Schemes ( Hybrid Scheme - Dynamic Asset Allocation or Balanced Advantage )
Open Ended Schemes ( Hybrid Scheme - Multi Asset Allocation )
Open Ended Schemes ( Hybrid Scheme - Arbitrage Fund )
Open Ended Schemes ( Hybrid Scheme - Equity Savings )
Open Ended Schemes ( Solution Oriented Scheme - Retirement Fund )
Open Ended Schemes ( Solution Oriented Scheme - Childrenâs Fund )
Open Ended Schemes ( Other Scheme - Index Funds )
Open Ended Schemes ( Other Scheme - Gold ETF )
Open Ended Schemes ( Other Scheme - FoF Overseas )
Open Ended Schemes ( Other Scheme - FoF Domestic )
Open Ended Schemes ( Equity Scheme - Flexi Cap Fund )
['Open Ended Schemes ( Debt Scheme - Overnight Fund )', 'Open Ended Schemes ( Debt Scheme - Liquid Fund )', 'Open Ended Schemes ( Other Scheme - Other  ETFs )', 'Open Ended Schemes ( Money Market )', 'Open Ended Schemes ( Equity Scheme - Multi Cap Fund )', 'Open Ended Schemes ( Equity Scheme - Large Cap Fund )', 'Open Ended Schemes ( Equity Scheme - Large & Mid Cap Fund )', 'Open Ended Schemes ( Equity Scheme - Mid Cap Fund )', 'Open Ended Schemes ( Equity Scheme - Small Cap Fund )', 'Open Ended Schemes ( Equity Scheme - Dividend Yield Fund )', 'Open Ended Schemes ( Equity Scheme - Value Fund )', 'Open Ended Schemes ( Equity Scheme - Contra Fund )', 'Open Ended Schemes ( Equity Scheme - Focused Fund )', 'Open Ended Schemes ( Equity Scheme - Sectoral/ Thematic )', 'Open Ended Schemes ( Equity Scheme - ELSS )', 'Open Ended Schemes ( Debt Scheme - Ultra Short Duration Fund )', 'Open Ended Schemes ( Debt Scheme - Low Duration Fund )', 'Open Ended Schemes ( Debt Scheme - Money Market Fund )', 'Open Ended Schemes ( Debt Scheme - Short Duration Fund )', 'Open Ended Schemes ( Debt Scheme - Medium Duration Fund )', 'Open Ended Schemes ( Debt Scheme - Medium to Long Duration Fund )', 'Open Ended Schemes ( Debt Scheme - Long Duration Fund )', 'Open Ended Schemes ( Debt Scheme - Dynamic Bond )', 'Open Ended Schemes ( Debt Scheme - Corporate Bond Fund )', 'Open Ended Schemes ( Debt Scheme - Credit Risk Fund )', 'Open Ended Schemes ( Debt Scheme - Banking and PSU Fund )', 'Open Ended Schemes ( Debt Scheme - Gilt Fund )', 'Open Ended Schemes ( Debt Scheme - Gilt Fund with 10 year constant duration )', 'Open Ended Schemes ( Debt Scheme - Floater Fund )', 'Open Ended Schemes ( Hybrid Scheme - Conservative Hybrid Fund )', 'Open Ended Schemes ( Hybrid Scheme - Balanced Hybrid Fund )', 'Open Ended Schemes ( Hybrid Scheme - Aggressive Hybrid Fund )', 'Open Ended Schemes ( Hybrid Scheme - Dynamic Asset Allocation or Balanced Advantage )', 'Open Ended Schemes ( Hybrid Scheme - Multi Asset Allocation )', 'Open Ended Schemes ( Hybrid Scheme - Arbitrage Fund )', 'Open Ended Schemes ( Hybrid Scheme - Equity Savings )', 'Open Ended Schemes ( Solution Oriented Scheme - Retirement Fund )', 'Open Ended Schemes ( Solution Oriented Scheme - Childrenâ\x80\x99s Fund )', 'Open Ended Schemes ( Other Scheme - Index Funds )', 'Open Ended Schemes ( Other Scheme - Gold ETF )', 'Open Ended Schemes ( Other Scheme - FoF Overseas )', 'Open Ended Schemes ( Other Scheme - FoF Domestic )', 'Open Ended Schemes ( Equity Scheme - Flexi Cap Fund )']
43

In [32]:
x =[]
for i in list:
   ap = i[21:-2]
   x.append(ap.split(" - "))

x_df = pd.DataFrame(x)
x_df

                           0                                               1
0                Debt Scheme                                  Overnight Fund
1                Debt Scheme                                     Liquid Fund
2               Other Scheme                                     Other  ETFs
3               Money Market                                            None
4              Equity Scheme                                  Multi Cap Fund
5              Equity Scheme                                  Large Cap Fund
6              Equity Scheme                            Large & Mid Cap Fund
7              Equity Scheme                                    Mid Cap Fund
8              Equity Scheme                                  Small Cap Fund
9              Equity Scheme                             Dividend Yield Fund
10             Equity Scheme                                      Value Fund
11             Equity Scheme                                     Contra Fund
12             Equity Scheme                                    Focused Fund
13             Equity Scheme                              Sectoral/ Thematic
14             Equity Scheme                                            ELSS
15               Debt Scheme                       Ultra Short Duration Fund
16               Debt Scheme                               Low Duration Fund
17               Debt Scheme                               Money Market Fund
18               Debt Scheme                             Short Duration Fund
19               Debt Scheme                            Medium Duration Fund
20               Debt Scheme                    Medium to Long Duration Fund
21               Debt Scheme                              Long Duration Fund
22               Debt Scheme                                    Dynamic Bond
23               Debt Scheme                             Corporate Bond Fund
24               Debt Scheme                                Credit Risk Fund
25               Debt Scheme                            Banking and PSU Fund
26               Debt Scheme                                       Gilt Fund
27               Debt Scheme        Gilt Fund with 10 year constant duration
28               Debt Scheme                                    Floater Fund
29             Hybrid Scheme                        Conservative Hybrid Fund
30             Hybrid Scheme                            Balanced Hybrid Fund
31             Hybrid Scheme                          Aggressive Hybrid Fund
32             Hybrid Scheme  Dynamic Asset Allocation or Balanced Advantage
33             Hybrid Scheme                          Multi Asset Allocation
34             Hybrid Scheme                                  Arbitrage Fund
35             Hybrid Scheme                                  Equity Savings
36  Solution Oriented Scheme                                 Retirement Fund
37  Solution Oriented Scheme                               Childrenâs Fund
38              Other Scheme                                     Index Funds
39              Other Scheme                                        Gold ETF
40              Other Scheme                                    FoF Overseas
41              Other Scheme                                    FoF Domestic
42             Equity Scheme                                  Flexi Cap Fund

In [31]:
y_df = x_df.groupby([0]).count()
print(y_df)

                           1
0
Debt Scheme               16
Equity Scheme             12
Hybrid Scheme              7
Money Marke                0
Other Scheme               5
Solution Oriented Scheme   2

In [40]:
x_df[x_df[0] == "Hybrid Scheme"]

                0                                               1
29  Hybrid Scheme                        Conservative Hybrid Fund
30  Hybrid Scheme                            Balanced Hybrid Fund
31  Hybrid Scheme                          Aggressive Hybrid Fund
32  Hybrid Scheme  Dynamic Asset Allocation or Balanced Advantage
33  Hybrid Scheme                          Multi Asset Allocation
34  Hybrid Scheme                                  Arbitrage Fund
35  Hybrid Scheme                                  Equity Savings

## List of Dates

In [11]:
date = [*df] # Extracting the keys from the dictionary
print(len(date))

1305

In [12]:
date_df = pd.DataFrame((date), columns=['date']) # Creating a DataFrame with the keys
date_df.tail() # Displaying the DataFrame

             date
1300  31-Mar-2025
1301  01-Apr-2025
1302  02-Apr-2025
1303  03-Apr-2025
1304  04-Apr-2025

In [8]:

new_df = []

for date in df.keys():
    for ele in df[date]:
        new_df.append({'date':date,'scheme_code': ele['scheme_code'],'nav': ele['nav']})

In [30]:
nav_df = pd.DataFrame(new_df,columns=['date', 'scheme_code', 'nav']) # Creating a new DataFrame with the desired columns
nav_df.head()

str

## Scheme Code

In [10]:
scheme_codes = nav_df['scheme_code'].unique() # Extracting unique scheme codes
print(len(scheme_codes))

14254

In [99]:
pivot_df = nav_df.pivot(index='date', columns='scheme_code', values='nav') # Pivoting the DataFrame
pivot_df = pivot_df.reset_index() # Resetting the index

a = pd.merge(date_df, pivot_df, on='date', how='left')
a.head()

KeyboardInterrupt:

# Mutual fund time series data

In [67]:
Mutual_funds_nav = a

In [55]:
fund_specs = {}
for date in df.keys():
    for ele in df[date]:
        if ele['scheme_code'] not in fund_specs:
            fund_specs[ele['scheme_code']] = {'shceme_name':ele['scheme_name'], 'category':ele['category'], 'amc':ele['amc']}

In [66]:
fund_specs_df = pd.DataFrame(fund_specs)
fund_specs_df = fund_specs_df.transpose() # Transposing the DataFrame
fund_specs_df = fund_specs_df.reset_index() # Resetting the index
fund_specs_df.columns = ['scheme_code', 'scheme_name', 'category', 'amc'] # Renaming the columns
fund_specs_df.head()

,scheme_code,scheme_name,category,amc
0,145488,ADITYA BIRLA SUN LIFE OVERNIGHT FUND- Direct ...,Open Ended Schemes ( Debt Scheme - Overnight F...,Aditya Birla Sun Life Mutual Fund
1,145489,ADITYA BIRLA SUN LIFE OVERNIGHT FUND- Direct ...,Open Ended Schemes ( Debt Scheme - Overnight F...,Aditya Birla Sun Life Mutual Fund
2,145482,ADITYA BIRLA SUN LIFE OVERNIGHT FUND- Regular...,Open Ended Schemes ( Debt Scheme - Overnight F...,Aditya Birla Sun Life Mutual Fund
3,145487,ADITYA BIRLA SUN LIFE OVERNIGHT FUND- Direct -...,Open Ended Schemes ( Debt Scheme - Overnight F...,Aditya Birla Sun Life Mutual Fund
4,145483,ADITYA BIRLA SUN LIFE OVERNIGHT FUND- Regular ...,Open Ended Schemes ( Debt Scheme - Overnight F...,Aditya Birla Sun Life Mutual Fund

In [68]:
Mutual_funds_specs = fund_specs_df

In [80]:
import json
with open('Mutual_funds_specs.json', 'w') as f:
    json.dump(fund_specs, f, indent=2)  # indent=2 makes it human-readable

In [90]:
Mutual_funds_nav.to_json('Mutual_funds_nav.json', orient='columns',indent = 2) # Saving the DataFrame to a JSON file